= Draft OGC API - Processes  Conformance Test Suite

== Scope

This executable test suite is for the OGC API - Processes draft standard.

Visit the http://opengeospatial.github.io/ets-ogcapi-processes10/[project documentation website TBD]
for more information, including the API documentation.

== 2 minutes method

Run the following commands:

[source,bash]
....
# Clone this repository
git clone https://github.com/opengeospatial/ets-ogcapi-processes10
cd ets-ogcapi-processes10

# Build the docker image
docker build . -t teamengine/ogcapi-processes:latest

# Run the docker container
docker run -d --name cite-teamengine -p 8080:8080 teamengine/ogcapi-processes:latest
....

From here, you can now access http://localhost:8080/teamengine to access the deployed teamengine with the OGC API - Processes Test Suite.


== How to build the test suite

The test suite is built using https://maven.apache.org/[Apache Maven v3].

== How to run the test suite
The options for running the suite are summarized in

include::src/site/asciidoc/how-to-run-the-tests.adoc[]

== How to contribute

If you would like to get involved, you can:

* https://github.com/opengeospatial/ets-ogcapi-processes10/issues[Report an issue] such as a defect or
an enhancement request
* Help to resolve an https://github.com/opengeospatial/ets-ogcapi-processes10/issues?q=is%3Aopen[open issue]
* Fix a bug: Fork the repository, apply the fix, and create a pull request
* Add new tests: Fork the repository, implement and verify the tests on a new topic branch,
and create a pull request (don't forget to periodically rebase long-lived branches so
there are no extraneous conflicts)
